version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    registries: "*"

    schedule:
      interval: "weekly"

    open-pull-requests-limit: 5

    reviewers:
      - VKalenski

    assignees:
      - VKalenski

    labels:
      - dependencies
      - security
