name: Build .NET Project

on:
  workflow_dispatch:

jobs:
  build:
    uses: VKalenski/GitHub-Actions-Templates/.github/workflows/build-dot-net.yaml@main
    with:
      project-name: './src/Project-DotNet-9'
      dotnet-version: '9.0.x'
