name: Build .NET Project

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag-version:
    uses: VKalenski/GitHub-Actions-Templates/.github/actions/tag-version@main

  build:
    needs: tag-version
    uses: VKalenski/GitHub-Actions-Templates/.github/workflows/dotnet-build.yaml@main
    with:
      project-name: './src/Project-DotNet-9'
      dotnet-version: '9.0.x'
