name: Push Docker Image and Security Scan with Trivy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Push Docker Image
        uses: VKalenski/GitHub-Actions-Templates/.github/actions/dotnet-docker@main
        with:
          docker-hub-account: vilislavkalenski
          image-name: project-dotnet-9
          image-version: latest
          project-path: ./src/Project-DotNet-9
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Scan Docker Image with Trivy
        uses: VKalenski/GitHub-Actions-Templates/.github/actions/dotnet-trivy@main
        with:
          docker-hub-account: vilislavkalenski
          image-name: project-dotnet-9
          image-version: latest
