name: Build and Security Scan with Trivy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t vilislavkalenski/project-dotnet-9:latest ./src/Project-DotNet-9

      - name: Push Docker image to Docker Hub
        run: |
          docker push vilislavkalenski/project-dotnet-9:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: "vilislavkalenski/project-dotnet-9:latest"
          exit-code: 1
          ignore-unfixed: true
          format: "table"
          severity: "CRITICAL,HIGH,MEDIUM,LOW"
          output: "aquasecurity-scan.txt"

      - name: Temporarily save Trivy results
        uses: actions/upload-artifact@v4
        with:
          name: "aquasecurity-scan"
          path: "./aquasecurity-scan.txt"
          retention-days: 1
